### ISSUE TITLE
Question: Can anyone tell me what I have to do if I have standard libvirt installed while using Openstack

### ISSUE THREAD

**Issue by tunicashashi** [projectacrn/acrn-libvirt#6]
I have installled openstack and want to continue using standard libvirt, can some one tell me what modification do I need to do for the ACRN support in it or currenlty only way it re-installting acrn-libvirt?

**Comment by peterfang** [comment]
Hi Yatindra,
Currently, standard libvirt does not include the ACRN driver. You'd have to use acrn-libvirt for now.
We have a guide here for your reference: https://projectacrn.github.io/latest/tutorials/setup_openstack_libvirt.html

**Comment by tunicashashi** [comment]
@peterfang 
Thanks for information. I had looked this tutorial guide and its quite infomative. But in my scenarion, i want to run Openstack which controlls KVM based vm in one nova node and ACRN based VM in anothe nova node simultaneously so i think, i can not patch the openstack as given in the link as it seems to me that qemu_kvm is not installed through this patch (https://raw.githubusercontent.com/projectacrn/acrn-hypervisor/master/doc/tutorials/0001-devstack-installation-for-acrn.patch). 
1. Can you suggest me how can I run two hypervisiors simultaneously? 
2. Can ACRN-Libvirt be used to have KVM-based VMs as well?

**Comment by peterfang** [comment]
Hi Yatindra,
1. It is theoretically possible to run multiple hypervisors in a single deployment, but we have never tested it.
2. Yes, just compile with the option "--with-qemu=yes"
