### ISSUE TITLE
Does dev-acrn-v4.0.0 or dev-acrn-v6.1.0 means these branch are forked from same release version of standard libvirt branch

### ISSUE THREAD

**Issue by tunicashashi** [projectacrn/acrn-libvirt#9]
I wanted to know which release version of starndard libvirt is used to create acrn-libvirt. How can I know?

**Comment by peterfang** [comment]
Hi Yatindra,

Our dev-acrn-v6.1.0 branch is branched out from the official tag v6.1.0:

tag v6.1.0
Tagger: Daniel Veillard <veillard@redhat.com>
Date:   Tue Mar 3 14:15:01 2020 +0100

RElease of libvirt-6.1.0
-----BEGIN PGP SIGNATURE-----

iQFLBAABCAA1FiEE20ZoG7ka3OoXD6LUFViLJllr6l0FAl5eWGAXHGRhbmllbC52
ZWlsbGFyZEB3My5vcmcACgkQFViLJllr6l3v8ggAoViauclAxi7audBaBhMNgVzO
reddZR1Y628UxlLyeB1QUYbM7YfvdByaiTW6d8Tx4/gYrffGm7zIzP0G5v6AjUoB
mAc/jmM8Npkawhxwxe2zQ82ud0152xR0XbcMZ6ms1d25F//0/3EhRDUGFSHcfUBI
y0VaHr6bAIxor0pz+O2wdjMRr5LMO/HpKOCmrYfIoiHIJTH8DsQd/UrVvAU45w47
bGw693Wvsj8NYxxdjt2ekUM4v+KuHXE4F8TXIfiIgihPtw4dF5wBbq/FT6q0mXwg
gxEZnLBEk5JgR6uvQCJYRs9K8Hf2nLF+lJvAUgnOYm0cQZ84WIykOgQuzSOENg==
=5Agq
-----END PGP SIGNATURE-----

**Comment by tunicashashi** [comment]
thanks for info
